weights: runs/train/no_autoanchor2/weights/best.pt
cfg: ''
data: data/gtsdb.yaml
hyp: data/hyps/hyp.finetune.yaml
epochs: 100
batch_size: 32
imgsz: 1360
rect: false
resume: false
nosave: false
noval: false
noautoanchor: true
evolve: null
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 8
project: runs/train
entity: null
name: size1360_hypfinetune
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
local_rank: -1
save_dir: runs/train/size1360_hypfinetune
